# TODO: Alocommon host builds

include $(ALONIRA_DIR)/alonira/vendor/genstone.mk

ALO_COMMON_SOURCES = $(wildcard $(ALONIRA_DIR)/alonira/alocommon/*.c)
ALO_COMMON_OBJECTS = $(ALO_COMMON_SOURCES:.c=$(TARGET_C32_OBJECT_SUFFIX))

ALO_COMMON_OUT = $(ALONIRA_DIR)/lib/$(TARGET_LIB_PREFIX)alocommon$(TARGET_STATIC_LIB_SUFFIX)

ALO_COMMON_COMMON_CFLAGS = $(GEN_CORE_CFLAGS) $(GENSTONE_CFLAGS)
ALO_COMMON_COMMON_LFLAGS = $(GEN_CORE_LFLAGS)

ALO_COMMON_INTERNAL_CFLAGS = -fsanitize=undefined,cfi $(GEN_CORE_DIAGNOSTIC_CFLAGS) $(ALO_COMMON_COMMON_CFLAGS)
ALO_COMMON_INTERNAL_LFLAGS = -fsanitize=undefined,cfi $(ALO_COMMON_COMMON_LFLAGS)

ALO_COMMON_CFLAGS = $(ALO_COMMON_COMMON_CFLAGS) -I$(ALONIRA_DIR)/alonira/alocommon/include
ALO_COMMON_LIBDIRS = $(ALONIRA_DIR)/lib $(GEN_CORE_LIBDIRS)
ALO_COMMON_LFLAGS = $(ALO_COMMON_COMMON_LFLAGS)

$(ALO_COMMON_OUT): TARGET_CFLAGS = $(ALO_COMMON_INTERNAL_CFLAGS)
$(ALO_COMMON_OUT): TARGET_LFLAGS =
$(ALO_COMMON_OUT): TARGET_LIBDIRS = $(GEN_CORE_LIBDIRS)
$(ALO_COMMON_OUT): $(ALO_COMMON_OBJECTS) $(GEN_CORE_LIB) | $(ALONIRA_DIR)/lib

.PHONY: alocommon
alocommon: $(ALO_COMMON_OUT)

.PHONY: test_alocommon
test_alocommon:

.PHONY: clean_alocommon
clean_alocommon:
	@$(ECHO) "$(ACTION_PREFIX)"
	-$(RM) $(ALO_COMMON_OBJECTS)
	-$(RM) $(ALO_COMMON_OUT)
	@$(ECHO) "$(ACTION_SUFFIX)"
