KERNEL_CFLAGS += -DGEN_THREAD_LOCAL=""

ALO_KERNEL_DIR = $(ALONIRA_DIR)/alonira/alokernel
ALO_KERNEL_TARGET_DIR = $(ALO_KERNEL_DIR)/$(KERNEL_TARGET)

ALO_KERNEL_CFLAGS = $(GEN_CORE_CFLAGS) $(GEN_BACKENDS_CFLAGS)

ALO_KERNEL_CFLAGS += -I$(ALO_KERNEL_DIR)/include
ALO_KERNEL_CFLAGS += -I$(ALO_KERNEL_TARGET_DIR)/include
ALO_KERNEL_CFLAGS += -I$(ALO_KERNEL_TARGET_DIR)/include/exposed

ifeq ($(BOOT_PROTOCOL),ULTRA)
	ALO_KERNEL_CFLAGS += $(ULTRA_CFLAGS)
endif

ALO_KERNEL_LFLAGS = $(GEN_CORE_LFLAGS) \
						-T$(ALO_KERNEL_DIR)/scripts/kernel-$(KERNEL_TARGET).ld

ALO_KERNEL_SOURCES = $(wildcard $(ALO_KERNEL_DIR)/*.c) \
						$(wildcard $(ALO_KERNEL_TARGET_DIR)/*.c) \
						$(wildcard $(ALO_KERNEL_DIR)/instrumentation/*.c)
ALO_KERNEL_OBJECTS = $(ALO_KERNEL_SOURCES:.c=$(OBJECT_SUFFIX))

ALO_KERNEL = $(ALONIRA_DIR)/boot/boot/alonira$(ELF_SUFFIX)

$(ALO_KERNEL): CFLAGS = $(GENSTONE_DIAGNOSTIC_CFLAGS) $(ALO_KERNEL_CFLAGS)
$(ALO_KERNEL): LFLAGS = $(ALO_KERNEL_LFLAGS)
$(ALO_KERNEL): LIBDIRS = $(GEN_CORE_LIBDIRS)
$(ALO_KERNEL): $(ALO_KERNEL_OBJECTS)

.PHONY: alokernel
alokernel: $(ALO_KERNEL)

.PHONY: test_alokernel
test_alokernel:

.PHONY: clean_alokernel
clean_alokernel:
	$(RM) $(ALO_KERNEL_OBJECTS)
	$(RM) $(ALO_KERNEL)
