GEN_BACKENDS_ALONIRA_CFLAGS += -I$(ALONIRA_DIR)/alonira/genbackends/override/include -I$(ALONIRA_DIR)/alonira/genbackends/include
GEN_BACKENDS_ALONIRA_LFLAGS += -lgenbackends
GEN_BACKENDS_ALONIRA_LIBDIRS += $(ALONIRA_DIR)/lib

GEN_BACKENDS_ALONIRA_SOURCES = $(wildcard $(ALONIRA_DIR)/alonira/genbackends/*.c)
GEN_BACKENDS_ALONIRA_OBJECTS = $(GEN_BACKENDS_ALONIRA_SOURCES:.c=$(KERNEL_OBJECT_SUFFIX))

GEN_BACKENDS_ALONIRA_LIB = $(ALONIRA_DIR)/lib/$(LIB_PREFIX)genbackends$(KERNEL_STATIC_LIB_SUFFIX)

GEN_BACKENDS_ALONIRA_INTERNAL_CFLAGS += $(GEN_BACKENDS_ALONIRA_CFLAGS) $(GENSTONE_DIAGNOSTIC_CFLAGS)
GEN_BACKENDS_ALONIRA_INTERNAL_LFLAGS += $(GEN_BACKENDS_ALONIRA_COMMON_LFLAGS)

GEN_BACKENDS_ALONIRA_SANITIZERS = undefined
