KERNEL_TANAI_SOURCES = $(wildcard $(ALONIRA_DIR)/alonira/tanai/*.c)
KERNEL_TANAI_OBJECTS = $(KERNEL_TANAI_SOURCES:.c=$(KERNEL_OBJECT_SUFFIX))
KERNEL_TANAI_LIB = $(ALONIRA_DIR)/lib/$(LIB_PREFIX)tanai$(KERNEL_STATIC_LIB_SUFFIX)

KERNEL_TANAI_SANITIZERS = undefined

KERNEL_TANAI_CFLAGS = $(GEN_CORE_CFLAGS) -I$(ALONIRA_DIR)/alonira/tanai/include
KERNEL_TANAI_LFLAGS = $(GEN_CORE_LFLAGS) -ltanai
KERNEL_TANAI_LIBDIRS = $(GEN_CORE_LIBDIRS) $(ALONIRA_DIR)/lib

$(KERNEL_TANAI_LIB): CFLAGS = $(GEN_CORE_CFLAGS) $(GENSTONE_DIAGNOSTIC_CFLAGS) -Wno-gnu-binary-literal
$(KERNEL_TANAI_LIB): LFLAGS = $(GEN_CORE_LFLAGS)
$(KERNEL_TANAI_LIB): LIBDIRS = $(KERNEL_TANAI_LIBDIRS)
$(KERNEL_TANAI_LIB): SANITIZERS = $(KERNEL_TANAI_SANITIZERS)
$(KERNEL_TANAI_LIB): $(KERNEL_TANAI_OBJECTS) $(GEN_CORE_LIB) | $(ALONIRA_DIR)/lib

.PHONY: kernel_tanai
kernel_tanai: $(KERNEL_TANAI_LIB)

.PHONY: test_kernel_tanai
test_kernel_tanai:

.PHONY: clean_kernel_tanai
clean_kernel_tanai:
	@$(ECHO) "$(ACTION_PREFIX)"
	-$(RM) $(KERNEL_TANAI_OBJECTS)
	-$(RM) $(KERNEL_TANAI_LIB)
	@$(ECHO) "$(ACTION_SUFFIX)"
