include $(ALONIRA_DIR)/alonira/genbackends_selector_alonira.mk

KERNEL_GEN_CORE_COMMON_CFLAGS = -DGEN_LOG_USE_STATIC_FORMAT_BUFFER=GEN_ENABLED

KERNEL_GEN_CORE_CFLAGS = $(KERNEL_GEN_CORE_COMMON_CFLAGS) -I$(GENSTONE_DIR)/genstone/gencore/include

KERNEL_GEN_CORE_INTERNAL_CFLAGS = $(KERNEL_GEN_CORE_COMMON_CFLAGS) $(GENSTONE_DIAGNOSTIC_CFLAGS) $(GEN_BACKENDS_ALONIRA_CFLAGS) -Wno-c++-compat -Wno-gnu-empty-struct
KERNEL_GEN_CORE_INTERNAL_LFLAGS = $(GEN_BACKENDS_ALONIRA_LFLAGS)

KERNEL_GEN_CORE_SANITIZERS = undefined

KERNEL_GEN_CORE_DISABLED_SOURCES = $(GENSTONE_DIR)/genstone/gencore/genmath.c
KERNEL_GEN_CORE_SOURCES = $(filter-out $(KERNEL_GEN_CORE_DISABLED_SOURCES),$(GEN_CORE_SOURCES))
KERNEL_GEN_CORE_OBJECTS = $(KERNEL_GEN_CORE_SOURCES:.c=$(KERNEL_OBJECT_SUFFIX))

KERNEL_GEN_CORE_LIB = $(GENSTONE_DIR)/lib/$(LIB_PREFIX)gencore$(KERNEL_STATIC_LIB_SUFFIX)

$(KERNEL_GEN_CORE_LIB): CFLAGS = $(KERNEL_GEN_CORE_INTERNAL_CFLAGS)
$(KERNEL_GEN_CORE_LIB): LFLAGS = $(KERNEL_GEN_CORE_INTERNAL_LFLAGS)
$(KERNEL_GEN_CORE_LIB): LIBDIRS = $(GEN_BACKENDS_ALONIRA_LIBDIRS)
$(KERNEL_GEN_CORE_LIB): SANITIZERS = $(KERNEL_GEN_CORE_SANITIZERS)
$(KERNEL_GEN_CORE_LIB): $(KERNEL_GEN_CORE_OBJECTS) $(GEN_BACKENDS_ALONIRA_LIB) | $(GENSTONE_DIR)/lib

.PHONY: kernel_gencore
kernel_gencore: $(KERNEL_GEN_CORE_LIB)

.PHONY: test_kernel_gencore
test_kernel_gencore:

.PHONY: clean_kernel_gencore
clean_kernel_gencore:
	@$(ECHO) "$(ACTION_PREFIX)"
	-$(RM) $(KERNEL_GEN_CORE_OBJECTS)
	-$(RM) $(KERNEL_GEN_CORE_LIB)
	@$(ECHO) "$(ACTION_SUFFIX)"
