TANAI_SOURCES = $(wildcard $(ALONIRA_DIR)/alonira/tanai/*.c)
TANAI_OBJECTS = $(TANAI_SOURCES:.c=$(OBJECT_SUFFIX))
TANAI_LIB = $(ALONIRA_DIR)/lib/$(LIB_PREFIX)tanai$(DYNAMIC_LIB_SUFFIX)

TANAI_WRITER_SOURCES =  $(wildcard $(ALONIRA_DIR)/alonira/tanai/writer/*.c)
TANAI_WRITER_OBJECTS = $(TANAI_WRITER_SOURCES:.c=$(OBJECT_SUFFIX))
TANAI_WRITER = $(ALONIRA_DIR)/tanai$(EXECUTABLE_SUFFIX)

TANAI_SANITIZERS = undefined,address

TANAI_CFLAGS = $(GEN_CORE_CFLAGS) -I$(ALONIRA_DIR)/alonira/tanai/include
TANAI_LFLAGS = $(GEN_CORE_LFLAGS) -ltanai
TANAI_LIBDIRS = $(GEN_CORE_LIBDIRS) $(ALONIRA_DIR)/lib

$(TANAI_LIB): CFLAGS = $(GEN_CORE_CFLAGS) $(GENSTONE_DIAGNOSTIC_CFLAGS)
$(TANAI_LIB): LFLAGS = $(GEN_CORE_LFLAGS)
$(TANAI_LIB): LIBDIRS = $(TANAI_LIBDIRS)
$(TANAI_LIB): SANITIZERS = $(TANAI_SANITIZERS)
$(TANAI_LIB): $(TANAI_OBJECTS) $(GEN_CORE_LIB) | $(ALONIRA_DIR)/lib

$(TANAI_WRITER): CFLAGS = $(TANAI_CFLAGS) $(GENSTONE_DIAGNOSTIC_CFLAGS)
$(TANAI_WRITER): LFLAGS = $(TANAI_LFLAGS)
$(TANAI_WRITER): LIBDIRS = $(TANAI_LIBDIRS)
$(TANAI_WRITER): SANITIZERS = $(TANAI_SANITIZERS)
$(TANAI_WRITER): $(TANAI_WRITER_OBJECTS) $(TANAI_LIB)

.PHONY: tanai
tanai: $(TANAI_LIB) $(TANAI_WRITER)

.PHONY: test_tanai
test_tanai:

.PHONY: clean_tanai
clean_tanai:
	@$(ECHO) "$(ACTION_PREFIX)"
	-$(RM) $(TANAI_OBJECTS)
	-$(RM) $(TANAI_LIB)
	-$(RM) $(TANAI_WRITER_OBJECTS)
	-$(RM) $(TANAI_WRITER)
	@$(ECHO) "$(ACTION_SUFFIX)"
